# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7faba22d689679979aa14f2ef7ea3c2652695e9cceeeef0910d739ca515ecf9e0f7dc404ca9ed0076cf615f67e1820bfa9a4282353a77d930c0366177d307c2a

test:
  secret_key_base: 1311a56eb5f24ddbf0aa06144f28e54a68d149fa85cafae05727c8796968028f651eabc23f2965e1cfd60e33e670a4bfb0149cb9100c9a6243fff1df14501ae8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
